#pragma once

/* This is a module that abstracts over different kinds of temperature sources,
 * currently physical "fan in" ports and "virtual" sources.
 * The sources are numbered as non-negative integers, starting with the "fan
 * in" sources and then the virtual.
 * They also have unique names, which are currently autogenerated.
 */

#define TEMPSRC_COUNT (FAN_IN_PORT_COUNT + TEMPSRC_VIRT_COUNT)

#include <stdint.h>

// Each degree Celsius is 1000
#define TEMP_DECIMAL_PLACES 3
typedef int32_t Temp;

Temp tempsrc_get_temp(int num);
const char *tempsrc_get_name(int num);
int tempsrc_by_name(char *name);

void tempsrc_virt_init(void);
/** num is the number given by tempsrc_by_name, *not* the number of the virt
 * tempsrc! */
void tempsrc_virt_set_temp(int num, Temp temp);
_Bool tempsrc_is_virt(int num);
